### PR TITLE
New function `findExcluded()`

### PR DESCRIPTION
**Pull request by magnusdv**
Experimenting with a new function identifying excluded pairings.
(Not ready for merge yet.)

### CODE REVIEW

**Comment by thoree** [comment]
Very useful function! I have started experimenting, more later!

**Comment by thoree** [comment]
I tested on a larger data set (see below) and `findExcluded` worked nicely.
Some malformed pedigrees (caused by Familias not recording sex of missing correctly)
were detected by `setSex(ghep$am, ids = ghep$missing, sex = 1)`.
and corrected in the fam file (is testing simillar to that performed by `setSex` performed
in `dvir` functions?) The top jointDVI assignment obtained with `limit = 0.5` now includes all Familias identifications and, not suprisingly some more. Here's the code:

``` r
library(dvir)
#> Loading required package: pedtools
ghep = familias2dvir("https://familias.name/Files/ghep4.fam", 
                     missingPrefix= "MP", familyPrefix = "F", 
                     refPrefix = "R", verbose = F)
ghep$pm = setSex(ghep$pm, ids = names(ghep$pm),  sex = 1)
ghep$am = setSex(ghep$am, ids = ghep$missing, sex = 1)
ghep
#> DVI dataset:
#>  76 victims: BS1_BS81_BS16_BS18_BS86, BS2, BS3_BS17_BS57, BS4, BS5, ..., BS85
#>  119 missing: MP1, MP2, MP3, MP4, MP5, ..., MP119
#>  286 typed refs: R1, R2, R3, R4, R5, ..., R286
#>  119 reference families

red = findExcluded(ghep)
#> Finding exclusions
#> Max incompatible markers = 2
#> 
#> PM samples excluded against all missing: None
#> 
#> Missing persons excluded against all PM samples:
#>   MP1
#>   MP2
#>   MP5
#>   MP8
#>   MP9
#>   MP11
#>   MP13
#>   MP14
#>   MP15
#>   MP16
#>   MP17
#>   MP18
#>   MP22
#>   MP23
#>   MP27
#>   MP28
#>   MP30
#>   MP32
#>   MP33
#>   MP35
#>   MP38
#>   MP39
#>   MP40
#>   MP42
#>   MP43
#>   MP45
#>   MP46
#>   MP47
#>   MP48
#>   MP50
#>   MP51
#>   MP52
#>   MP53
#>   MP55
#>   MP56
#>   MP57
#>   MP58
#>   MP59
#>   MP60
#>   MP61
#>   MP62
#>   MP64
#>   MP65
#>   MP66
#>   MP67
#>   MP68
#>   MP70
#>   MP71
#>   MP73
#>   MP75
#>   MP80
#>   MP82
#>   MP84
#>   MP87
#>   MP88
#>   MP91
#>   MP93
#>   MP94
#>   MP95
#>   MP97
#>   MP98
#>   MP99
#>   MP100
#>   MP101
#>   MP102
#>   MP104
#>   MP106
#>   MP109
#>   MP111
#>   MP112
#>   MP114
#>   MP115
#>   MP117
#> 
#> Reducing DVI dataset
#> Removing AM families with no missing persons: 1, 2, 5, 8, 9, 11, 13, 14, 15, 16, 17, 18, 22, 23, 27, 28, 30, 32, 33, 35, 38, 39, 40, 42, 43, 45, 46, 47, 48, 50, 51, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 70, 71, 73, 75, 80, 82, 84, 87, 88, 91, 93, 94, 95, 97, 98, 99, 100, 101, 102, 104, 106, 109, 111, 112, 114, 115, 117
#> 
#> In total 8500 pairings excluded
ghepR = red$dviReduced
ncomb(0, 0, length(ghep$pm), length(ghep$missing))
#> [1] 4.941164e+144
ncomb(0, 0, length(ghepR$pm), length(ghepR$missing))
#> [1] 2.971684e+79
```

<sup>Created on 2022-11-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by magnusdv** [comment]
Nice. BTW, note the difference (in runtime) between the following commands, which give identical results:

```r
res1 = jointDVI(red$dviReduced, limit = 0.5)
res2 = jointDVI(red$dviReduced, pairings = red$pairings, limit = 0.5)
```

The second version is much faster, since it doesn't include excluded pairings.

I guess `findExcluded()` could be incorporated in the `jointDVI()` pipeline, before (or after??) `findUndisputed()`.

**Comment by thoree** [comment]
Yes, substantial difference, 1.46 min and 28 sec, respectively. And yes,
it would be nice to have `findExcluded()` in the loop, before `findUndisputed()` seems natural.

**Pull request merged**
